---
- hosts: all
  vars:
    remote_user: <user_name>
  tasks:
          # upload ssh key                
          - authorized_key:
                  user: {{remote_user}}
                  state: present
                  manage_dir: yes
                  key: "{{ lookup('file', '/home/{{remote_user}}/.ssh/id_rsa.pub') }}"
