---
- hosts: all
  tasks:
   # upload ssh key                
   - authorized_key:
       user: "{{ansible_user}}"
       state: present
       manage_dir: yes
       key: "{{ lookup('file', '/home/<current_user>/.ssh/id_rsa.pub') }}"
