---
- hosts: all
  remote_user: <user_name>
  tasks:
          # upload ssh key                
          - authorized_key:
                  user: <user_name>
                  state: present
                  manage_dir: yes
                  key: "{{ lookup('file', '/home/<user_name>/.ssh/id_rsa.pub') }}"
